# @package _group_
_target_: dpr_scale.datamodule.dpr.DenseRetrieverJsonlDataModule
train_path: "/private/home/barlaso/repos/DPR/data/retriever/nq-train.jsonl"
val_path: "/private/home/barlaso/repos/DPR/data/retriever/nq-dev.jsonl"
test_path: "/private/home/barlaso/repos/DPR/data/retriever/nq-dev.jsonl"
batch_size: 2
